---
dev_name: cf-postgres
latest_release_filename: /Users/mwright/Documents/PCF/BOSH-releases/cf-bosh-workshop/bosh-postgres-release/complete/postgres-bosh-release/dev_releases/cf-postgres/cf-postgres-0+dev.2.yml
